#! /bin/bash

# set -o xtrace   # Write all commands first to stderr
set -o errexit  # Exit the script with error if any of the commands fail

# make sure there are no node/npm in path
PATH=$(echo "$PATH" | sed -e 's/:\/opt\/node\/bin$//')

PROJECT_DIRECTORY="$(pwd)/node-mongodb-native"
NODE_ARTIFACTS_PATH="${PROJECT_DIRECTORY}/node-artifacts"

export PROJECT_DIRECTORY

export NVM_DIR="${NODE_ARTIFACTS_PATH}/nvm"
[ -s "${NVM_DIR}/nvm.sh" ] && \. "${NVM_DIR}/nvm.sh"

node "integrations/$DRIVER_DIRNAME/workload-executor.js" "$1" "$2"