#! /bin/bash

# set -o xtrace   # Write all commands first to stderr
set -o errexit  # Exit the script with error if any of the commands fail

export OUTPUT_DIRECTORY="$(pwd)"
export PROJECT_DIRECTORY="$(pwd)/node-mongodb-native"
export NODE_ARTIFACTS_PATH="${PROJECT_DIRECTORY}/node-artifacts"

cd ${PROJECT_DIRECTORY}
echo $1
echo $2
UTR_TRACE="true" OUTPUT_DIRECTORY=$OUTPUT_DIRECTORY DRIVERS_ATLAS_TESTING_URI=$1 WORKLOAD_SPECIFICATION=$2 npm run check:drivers-atlas-testing
