
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
  - id: check-added-large-files
  - id: check-case-conflict
  - id: check-toml
  - id: check-yaml
    exclude: kubernetes/kind/mongodb.yml
  - id: debug-statements
  - id: end-of-file-fixer
    exclude: WHEEL
    exclude_types: [json]
  - id: forbid-new-submodules
  - id: trailing-whitespace
    exclude: .patch
    exclude_types: [json]

- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.1.8
  hooks:
    - id: ruff
      args: ["--fix", "--show-fixes"]
    - id: ruff-format

- repo: https://github.com/adamchainz/blacken-docs
  rev: "1.16.0"
  hooks:
  - id: blacken-docs
    additional_dependencies:
    - black==22.3.0

- repo: https://github.com/pre-commit/pygrep-hooks
  rev: "v1.10.0"
  hooks:
    - id: rst-backticks
    - id: rst-directive-colons
    - id: rst-inline-touching-normal

- repo: https://github.com/rstcheck/rstcheck
  rev: v6.2.0
  hooks:
  - id: rstcheck
    additional_dependencies: [sphinx]
    args: ["--ignore-directives=doctest,testsetup,todo,automodule","--ignore-substitutions=release", "--report-level=error"]

- repo: https://github.com/executablebooks/mdformat
  rev: 0.7.17
  hooks:
    - id: mdformat
      args: ["--wrap=120"]
      additional_dependencies:
        [mdformat-gfm]

- repo: https://github.com/tcort/markdown-link-check
  rev: v3.11.2
  hooks:
    - id: markdown-link-check

# We use the Python version instead of the original version which seems to require Docker
# https://github.com/koalaman/shellcheck-precommit
- repo: https://github.com/shellcheck-py/shellcheck-py
  rev: v0.9.0.6
  hooks:
    - id: shellcheck
      name: shellcheck
      args: ["--severity=error"]
      stages: [manual]

- repo: https://github.com/PyCQA/doc8
  rev: v1.1.1
  hooks:
    - id: doc8
      args: ["--ignore=D001"]  # ignore line length
      stages: [manual]

- repo: https://github.com/python-jsonschema/check-jsonschema
  rev: 0.27.3
  hooks:
    - id: check-github-workflows
      args: ["--verbose"]
      stages: [manual]

- repo: https://github.com/ariebovenberg/slotscheck
  rev: v0.17.1
  hooks:
  - id: slotscheck
    files: \.py$
    exclude: "^(tests|docs|workloads|integrations)/"
    stages: [manual]
    args: ["--no-strict-imports"]

- repo: https://github.com/codespell-project/codespell
  rev: "v2.2.6"
  hooks:
  - id: codespell
    # Example of error to justify the exceptions:
    # - docs/source/integration-guide.rst:170: re-use ==> reuse
    args: ["-L", "re-use"]
