matrix:
  include:
    - name: "build docs and push to gh-pages"
      dist: xenial
      language: python
      python:
        - 3.7
      install:
        - pip3 install sphinx
      script:
        - cd docs/ && make html && echo " " > build/html/.nojekyll
      deploy:
        provider: pages
        skip_cleanup: true
        github_token: $GITHUB_TOKEN
        keep_history: false
        local_dir: docs/build/html/
        target_branch: gh-pages
        on:
          branch: master
