#! /bin/bash

# set -o xtrace   # Write all commands first to stderr
set -o errexit  # Exit the script with error if any of the commands fail

export PATH=$GOROOT/bin:$PATH
cd integrations/$DRIVER_DIRNAME

./executor "$1" "$2"
