#!/bin/bash

set -o errexit  # Exit the script with error if any of the commands fail

# TODO: Remove this after https://jira.mongodb.org/browse/BUILD-13026 is resolved
if [ -d "/opt/php/${PHP_VERSION}-64bit/bin" ]; then
    PHP_PATH="/opt/php/${PHP_VERSION}-64bit/bin"
else
    # Try to find the newest version matching our constant
    PHP_PATH=`find /opt/php/ -maxdepth 1 -type d -name "${PHP_VERSION}*-64bit" -print | sort -V -r | head -1`
fi

if [ ! -d "${PHP_PATH}" ]; then
    echo "Could not find PHP binaries for version ${PHP_VERSION}. Listing available versions..."
    ls -1 /opt/php
    exit 1
fi

export PATH=${PHP_PATH}/bin:${PATH}

php -d memory_limit=-1 "integrations/${DRIVER_DIRNAME}/workload-executor.php" "$1" "$2"
